module.exports = function generateClaimsPrompt(problemStatement, productDescription) {
  return `
You are an AI assistant helping to evaluate a potential product idea.

Context:
- This product is being developed by Mitsubishi’s Innovation Lab.
- Problem Statement: ${problemStatement}
- Product Description: ${productDescription}

We have four fixed claims (as questions):
1. "Is the target market for this product sufficiently large?"
2. "Is the target market for this product growing at a significant rate?"
3. "Is the product technically feasible?"
4. "Does the product offer a distinct competitive advantage over existing solutions?"

Now, provide ONE additional claim (Claim #5) as a single, concise question directly related to the product’s viability and suitability for Mitsubishi. Follow these rules for Claim #5:
- It must be relevant to the product and context provided above.
- It must not be redundant with Claims 1-4.
- It should not be overly wordy—keep it short and direct.
- Return all five claims together as a numbered list of questions, with Claim #5 generated by you now.

Output only the list of five claims as questions, nothing else.
`;
};
